version: "3.7"

services:
  proxy:
    container_name: eshop-proxy
    image: vgorlanov/eshop-proxy:prod
    links:
      - php
    ports:
      - "80:80"

  php:
    container_name: eshop-backend
    image: vgorlanov/eshop-backend:prod
    extra_hosts:
      - localhost:${NGINX_IP}
    depends_on:
      - db
      - elastic
    environment:
      - HOST_NAME=http://vgorlanov.ru

  composer:
    container_name: composer
    image: composer:1
    depends_on:
      - php
    volumes:
      - .:/var/www/backend
    working_dir: /var/www/backend

  db:
    image: library/mysql:8
    container_name: eshop-db
    ports:
      - "3306:3306"
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eshop

  front:
    container_name: eshop-front
    image: vgorlanov/eshop-front:prod

  admin:
    container_name: eshop-admin
    image: vgorlanov/eshop-admin:prod

  elastic:
    container_name: eshop-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    environment:
      - node.name=es
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es
      - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  redis:
    container_name: eshop-redis
    image: redis:6.0-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - rsdata:/data

volumes:
  dbdata:
    driver: local
  esdata:
    driver: local
  rsdata:
    driver: local
